export const store = {
    account:{},
    userTermsAndConditions:[],
    registration:{},
    property:{  
        propertyTypes:[],
        propertyFeatures:[],
        countryList:[],
        selectedPropertyType:'',
        selectedBookingType:[],
        title:'',
        address:{   aptFloor: '', 
                    streetAddress: '', 
                    addressOne: '', 
                    addressTwo: ''},
        country:{},
        city:{},
        district:{},
        thana:{},
        timeZone:{},
        zipCode:'',
        location:{},
        roomCount:[],
        bedCount:[],
        guestCount:[],
        homeRules:[],
        checkInTime:[],
        checkOutTime:[],
        selectedPropertyFeatures:[],
        propertyDescription:'',
        images:[],
        rentInfo:{}
    },
};